# Generated by Django 4.2.6 on 2023-11-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mensaje",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenido", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="UserData",
        ),
    ]
