# Generated by Django 4.2.3 on 2023-11-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0003_mensaje_delete_message_delete_userdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="mensaje",
            name="respuesta",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
