# Generated by Django 4.2.6 on 2023-11-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0004_mensaje_respuesta"),
    ]

    operations = [
        migrations.CreateModel(
            name="Linea_Comando",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comando", models.TextField()),
                ("parametros", models.TextField()),
            ],
        ),
    ]
