# Generated by Django 4.2.6 on 2023-11-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0005_linea_comando"),
    ]

    operations = [
        migrations.CreateModel(
            name="Registro_IP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("IP", models.TextField()),
                ("fecha", models.DateTimeField(auto_now_add=True)),
                ("contenedor1", models.TextField(blank=True, null=True)),
                ("contenedor2", models.TextField(blank=True, null=True)),
                ("contenedor3", models.TextField(blank=True, null=True)),
                ("contenedor4", models.TextField(blank=True, null=True)),
                ("contenedor5", models.TextField(blank=True, null=True)),
                ("contenedor6", models.TextField(blank=True, null=True)),
                ("contenedor7", models.TextField(blank=True, null=True)),
                ("contenedor8", models.TextField(blank=True, null=True)),
                ("contenedor9", models.TextField(blank=True, null=True)),
                ("contenedor10", models.TextField(blank=True, null=True)),
                ("contenedor11", models.TextField(blank=True, null=True)),
                ("contenedor12", models.TextField(blank=True, null=True)),
                ("contenedor13", models.TextField(blank=True, null=True)),
                ("contenedor14", models.TextField(blank=True, null=True)),
                ("contenedor15", models.TextField(blank=True, null=True)),
                ("reporte", models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
