# Generated by Django 4.2.6 on 2023-11-03 11:27

from django.db import migrations
import frontend.models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0006_registro_ip"),
    ]

    operations = [
        
    ]
