# Generated by Django 4.2.6 on 2023-11-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0007_alter_mensaje_fecha_alter_registro_ip_fecha"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro_ip",
            name="empresa",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="nombre",
            field=models.TextField(blank=True, null=True),
        ),
    ]
