# Generated by Django 4.2.6 on 2023-11-03 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0008_registro_ip_empresa_registro_ip_nombre"),
    ]

    operations = [
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta10",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta11",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta12",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta13",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta14",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta15",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta5",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta6",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta7",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta8",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="registro_ip",
            name="respuesta9",
            field=models.TextField(blank=True, null=True),
        ),
    ]
