# Generated by Django 4.2.6 on 2023-11-04 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0010_registro_ip_recomendaciones_registro_ip_resultado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registro_ip",
            name="reporte",
            field=models.TextField(blank=True, null=True),
        ),
    ]
